version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly" # can be `daily` or `monthly` also
    open-pull-requests-limit: 10
    ignore:
      # Add the dependencies you want to ignore here.
