---
blank_issues_enabled: false
contact_links:
  - name: Satoru Keeper Community Support
    url: https://github.com/keep-starknet-strange/satoru-keeper/discussions
    about: Please ask and answer questions here.
